### PR TITLE
Me gusta Ember 2.10

### LINKED ISSUE #282: Upgrade to ember 2.10

### PR DESCRIPTION
**Pull request by gzurbach**
Closes #282

### CODE REVIEW

**Comment by kiwiupover** [comment]
Awesome.

How much smaller is the app.js size? 
Does it feel faster?

**Comment by gzurbach** [comment]
Is it supposed to be smaller? Do they get rid of a bunch of code? I was on 2.5 before.

It doesn't feel much faster but the app wasn't that slow either before. I ran into issues with this bug https://github.com/emberjs/ember.js/issues/13948 and couldn't find an elegant solution. I had to add a `Ember.run.next`.

**Comment by kiwiupover** [comment]
The templates are no longer functions but a small JSON payload that are then lazily evaluated at the time they are rendered. Some people are finding a 40% smaller app.js size. That would be your webapp.js  your vendor.js might be a bit bigger. 

You can find out by running `ember asset-sizes`

**Comment by eriktrom** [comment]
:wave:

**Comment by gzurbach** [comment]
Trom! I miss you buddy 🙂

**Pull request merged**
